# Generated by Django 4.1.6 on 2023-02-20 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='last_litter_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 4, 53, 535692, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
