# Generated by Django 4.1.6 on 2023-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_creature_last_litter_refill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='advice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creature',
            name='creature_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='wearing_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
