# Generated by Django 4.1.6 on 2023-02-20 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0003_alter_advice_advice_id_alter_creature_creature_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='last_food_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 32, 31, 150095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_litter_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 32, 31, 150095, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_thirst_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 32, 31, 150095, tzinfo=datetime.timezone.utc)),
        ),
    ]
