# Generated by Django 4.1.6 on 2023-02-20 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_alter_creature_last_food_refill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='creature_id',
            new_name='creature',
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_food_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 42, 8, 90954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_litter_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 42, 8, 90954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_thirst_refill',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 16, 42, 8, 90954, tzinfo=datetime.timezone.utc)),
        ),
    ]
