# Generated by Django 4.1.5 on 2023-02-22 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0007_locationbin_locationfountain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='last_food_refill',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_litter_refill',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='creature',
            name='last_thirst_refill',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
