# Generated by Django 4.1.6 on 2023-02-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0008_alter_creature_last_food_refill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='advice',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='advice',
            name='source',
            field=models.CharField(default='', max_length=250),
        ),
    ]
