# Generated by Django 4.1.6 on 2023-03-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0009_advice_link_alter_advice_content_alter_advice_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-points']},
        ),
    ]
