# Generated by Django 4.1.5 on 2023-03-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('colour_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('colour_hex_val', models.CharField(max_length=10)),
                ('colour_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='creature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climate.creature'),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climate.item'),
        ),
    ]
