# Generated by Django 4.1.5 on 2023-03-15 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0011_colour_alter_item_item_cost_alter_wearing_creature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='colour_hex_val_patch',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='eye_colour',
            field=models.ForeignKey(default='blue', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='eye_colour', to='climate.colour'),
        ),
        migrations.AddField(
            model_name='creature',
            name='fur_colour',
            field=models.ForeignKey(default='black', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='fur_colour', to='climate.colour'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pause_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='climate.item'),
        ),
    ]
