# Generated by Django 4.1.6 on 2023-03-13 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0011_colour_alter_item_item_cost_alter_wearing_creature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pause_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
