# Generated by Django 4.1.5 on 2023-03-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0012_remove_creature_colour_creature_eye_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='colour_hex_val_patch',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='wearing',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='climate.item'),
        ),
    ]
