# Generated by Django 4.1.5 on 2023-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0012_remove_creature_colour_remove_item_item_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='colour',
        ),
        migrations.AddField(
            model_name='item',
            name='scale',
            field=models.IntegerField(default=120),
        ),
    ]
