# Generated by Django 4.1.5 on 2023-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0013_remove_creature_colour_remove_item_item_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_img',
        ),
    ]
