# Generated by Django 4.1.5 on 2023-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0013_colour_colour_hex_val_patch_alter_wearing_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour_hex_val_patch',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
