# Generated by Django 4.1.5 on 2023-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0015_alter_colour_colour_hex_val_patch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_img',
        ),
        migrations.AlterField(
            model_name='colour',
            name='colour_hex_val_patch',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
